[package]
name = "EyeOxide"
version = "0.1.0"
edition = "2021"

[dependencies]
colorful = "0.3.2"
dotenvy = "0.15.7"
ipinfo = "3.0.0"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["full"] }
